AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

    FunctionName:
        Type: AWS::Serverless::Function
        Properties:
           Handler: org.yangdeal.Hello::handleRequest
           Runtime: java8
           CodeUri: build/distributions/lambda_hello-1.0.zip
           Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /test
                  Method: get